### ISSUE TITLE
Manual logging of time

### ISSUE THREAD

**Issue by tuxflo** [fathomssen/redtimer#8] opened 2016-04-21 19:51 UTC
Hey!
Thanks for the great tool. It does exactly what I was looking for.
However, it would be a nice feature if one could add manual time entries without tracking.
For example if one forgot to push the play button.

Greetings from germany,
Flo

**Comment by fathomssen** [comment] 2016-04-21 19:57
Hi Flo

I thought about that as well and I see three ways of implementing it:

- A "plus" button which enables you to add time to the currently tracked time
- A "plus" button which opens a new window to manually log time
- Or even simpler: Let the user edit the timer field manually.

Greetings from Hamburg :-p
Freddy

**Comment by tuxflo** [comment] 2016-04-21 20:03
I think the last solution would be the most intuitive one. If I have some spare time I would like contribute to your project.

**Comment by fathomssen** [comment] 2016-04-21 20:07
Sure, help is always welcome. For the last solution to work properly, we will have to use a time field instead of a plain text field.

Have you ever used Qt.ImhTime (http://doc.qt.io/qt-5/qml-qtquick-controls-textfield.html#inputMethodHints-prop)?

**Comment by tuxflo** [comment] 2016-04-21 20:30
Nope... I didn't work with QML at all. In the past I only used the "classic" Qt-GUI structure. But this seems to be a good way to get started with QML ;)

**Comment by fathomssen** [comment] 2016-05-09 05:57
Hi @tuxflo 

The issue is resolved in version 0.1.3 (https://github.com/fathomssen/redtimer/releases/tag/v0.1.3). I am still using the plain text field but when time parsing fails, I simply go on with the old tracked time and the user can try to enter a time once more.

Best regards
Frederick Thomssen

**Closed by fathomssen** 2016-05-09 05:57 UTC
Labels: enhancement

**Comment by fathomssen** [comment] 2016-05-10 05:27
Fyi: Currently, you have to press Enter after changing the time. In the next version, leaving the text field (e.g. by clicking on a button) will suffice.
